baseURL = 'https://portfolio.marty-manguerra.workers.dev/'
languageCode = 'en-us'
title = 'My Portfolio'
theme = 'portfolio'

[params]
  tagline = 'Personal site & blog'
  description = 'A personal portfolio and blog'

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true

[menu]

  [[menu.main]]
    name = 'Home'
    url = '/'
    weight = 1

  [[menu.main]]
    name = 'About'
    url = '/about/'
    weight = 2

  [[menu.main]]
    name = 'Learning'
    url = '/learning/'
    weight = 3

  [[menu.main]]
    name = 'Courses'
    url = '/courses/'
    weight = 4

  [[menu.main]]
    name = 'Projects'
    url = '/projects/'
    weight = 5

  [[menu.main]]
    name = 'Posts'
    url = '/posts/'
    weight = 6

  [[menu.sidebar]]
    name = 'About Me'
    url = '/about/'
    weight = 1

  [[menu.sidebar]]
    name = 'Learning'
    url = '/learning/'
    weight = 2

  [[menu.sidebar]]
    name = 'Courses'
    url = '/courses/'
    weight = 3

  [[menu.sidebar]]
    name = 'Projects'
    url = '/projects/'
    weight = 4

  [[menu.sidebar]]
    name = 'Posts'
    url = '/posts/'
    weight = 5

  [[menu.footer]]
    name = 'About'
    url = '/about/'
    weight = 1

  [[menu.footer]]
    name = 'Learning'
    url = '/learning/'
    weight = 2

  [[menu.footer]]
    name = 'Courses'
    url = '/courses/'
    weight = 3

  [[menu.footer]]
    name = 'Projects'
    url = '/projects/'
    weight = 4

  [[menu.footer]]
    name = 'Posts'
    url = '/posts/'
    weight = 5

[caches]
  [caches.images]
    dir = ':cacheDir/images'

